import Head from "next/head";
import styles from "../styles/Home.module.css";
import Map from "@/components/Map";
import ControlPanel from "@/components/ControlPanel";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<Map
					initialViewState={{
						longitude: -100,
						latitude: 40,
						zoom: 3.5,
					}}
				/>
				<ControlPanel />
			</main>
		</>
	);
}
